// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZviMnc5EYiVTiUbQamdXLs-s7KjfZ6_U',
    appId: '1:68777440413:web:24423fdbc354dd3a6a1074',
    messagingSenderId: '68777440413',
    projectId: 'smartpot-944f9',
    authDomain: 'smartpot-944f9.firebaseapp.com',
    storageBucket: 'smartpot-944f9.appspot.com',
    measurementId: 'G-LR8ZN8KP70',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwIN0JJ2_NSO_zvE04hudMoWLOnEK14I',
    appId: '1:68777440413:ios:9406f690e31a06236a1074',
    messagingSenderId: '68777440413',
    projectId: 'smartpot-944f9',
    storageBucket: 'smartpot-944f9.appspot.com',
    iosBundleId: 'com.example.smartpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJwIN0JJ2_NSO_zvE04hudMoWLOnEK14I',
    appId: '1:68777440413:ios:9406f690e31a06236a1074',
    messagingSenderId: '68777440413',
    projectId: 'smartpot-944f9',
    storageBucket: 'smartpot-944f9.appspot.com',
    iosBundleId: 'com.example.smartpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZviMnc5EYiVTiUbQamdXLs-s7KjfZ6_U',
    appId: '1:68777440413:web:d5cb166a384e03f16a1074',
    messagingSenderId: '68777440413',
    projectId: 'smartpot-944f9',
    authDomain: 'smartpot-944f9.firebaseapp.com',
    storageBucket: 'smartpot-944f9.appspot.com',
    measurementId: 'G-CGYL7FQE0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyeJoGFyxa7OMINWrYAdA0fGqoIMfGzCw',
    appId: '1:68777440413:android:50bab2016b4e00bf6a1074',
    messagingSenderId: '68777440413',
    projectId: 'smartpot-944f9',
    storageBucket: 'smartpot-944f9.appspot.com',
  );

}